trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.x'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build $(buildConfiguration)'

- script: >
    dotnet test
    --configuration $(buildConfiguration)
    --no-build
    --logger "trx"
  displayName: 'dotnet test'

- task: PublishTestResults@2
  displayName: 'Publish test results (TRX)'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/**/*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    mergeTestResults: true
    testRunTitle: 'Unit Tests'
